exicom23and22
IEEE-SB-GEC-Palakkad/ieee-sb-website pull request #1
Opened 2024-08-04 15:39 UTC by jubuhan

2024-08-04 15:40 UTC, jubuhan commented
Exicome Details 22 and 23

2024-08-04 16:04 UTC, anima-regem requested changes
@jubuhan Can you please increase the sizes of the images on the **Execom 23** and **Execom 24** posters? Those landscape images are not clearly visible. If possible **you can take full screen** with for those banner type images. `w-full` or `w-1/2` whichever looks good will be fine.

2024-08-04 16:06 UTC, anima-regem commented on src/components/Execom23/Execom23.jsx
`w-full` will be better for the banner type images.

2024-08-04 16:07 UTC, anima-regem commented on src/components/Exicom22/Exicom22.jsx
`w-full` will be better for the banner type images.

2024-08-05 17:07 UTC, anima-regem approved these changes
Looks good!

2024-08-05 17:07 UTC, merged